
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-filestore
  namespace: moodle
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: pv-filestore
  resources:
    requests:
      storage: 300Gi
    limits:
      storage: 500Gi