
[moodle]

user = www
group = www

; This must be configured on nginx (fastcgi_pass unix:/var/run/php8.1-fpm-moodle.sock;)
listen = /var/run/php8.1-fpm-moodle.sock
listen.owner = www
listen.group = www

listen.allowed_clients = 127.0.0.1:8080

php_admin_value[disable_functions] = exec,passthru,shell_exec,system
php_admin_flag[allow_url_fopen] = off

; Process Manager
pm = static
pm.max_children = 3
pm.start_servers = 4
pm.min_spare_servers = 4
pm.max_spare_servers = 8
pm.process_idle_timeout = 15s
pm.max_requests = 256

pm.status_path = /fpm-status
ping.path = /fpm-ping

security.limit_extensions = .php

request_terminate_timeout = 1200
