
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: moodle-ingress-frontendconfig-https
  namespace: moodle
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
